### ISSUE TITLE
pipeline has no release, but no UNDER CONSTRUCTION warning

### ISSUE THREAD

**Issue by maxulysse** [nf-core/gwas#10]
## Check Documentation

I have checked the following places for your error:

- [ ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ ] [nf-core/gwas pipeline documentation](https://nf-co.re/nf-core/gwas/usage)

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: 
2. See error: 

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 
- Image tag:

**Comment by abhi18av** [comment]
The `About` section has now been updated. Closing this issue now.
